import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx </code>
            or do something else, I couldn't care less. But I think we can all chuckle at the fact that I made a whole ass website for like 4 links
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Built by mike, but really it was scaffolded but it is hosted on ----{'>'}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://www.freecodecamp.org/news/how-to-contribute-to-open-source-projects-beginners-guide/ "
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Basics <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              The shit you should have read before today.
            </p>
          </a>

          <a
            href="https://github.com/firstcontributions/first-contributions"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Tutorial <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Still scared?? Do this cowardly tutorial.
            </p>
          </a>

          <a
            href="https://firstcontributions.github.io/#project-list"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Projects <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Someone else's better website with a bunch of known opensource projects to check out
            </p>
          </a>

          <a
            href="https://github.com/cirkonis/open-source-workshop/contribute"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Contribute to this code <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              It's fun, easy, and educational?
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
